### ISSUE TITLE
Failure to convert script.

### ISSUE THREAD

**Issue by GalacticB69** [JessaTehCrow/lynie#2]
**Describe the bug**
It doesn't like certain script formatting.

**To Reproduce**
Msg me on discord for my exact steps as they include some test source code that I'd rather remain private for the time being
GalacticB69#4729

**Expected behavior**
It doesn't error and produces a functioning script.

**Additional context**
Traceback: 
```
Traceback (most recent call last):
  File "/****/lynie/example.py", line 8, in <module>
    line = lynie.parse_file(filename)
  File "/****/lynie/lynie/lynie.py", line 408, in parse_file
    out = _parse_body(parsed_ast.body,force_list=True)
  File "/****/lynie/lynie/lynie.py", line 387, in _parse_body
    temp = parser[type(x)](x)
  File "/****/lynie/lynie/lynie.py", line 346, in _def_parse
    code = _parse_body(body.body)
  File "/****/lynie/lynie/lynie.py", line 387, in _parse_body
    temp = parser[type(x)](x)
  File "/****/lynie/lynie/lynie.py", line 310, in _for_parse
    out = _parse_body(body.body)
  File "/****/lynie/lynie/lynie.py", line 387, in _parse_body
    temp = parser[type(x)](x)
  File "/****/lynie/lynie/lynie.py", line 286, in _assign_parse
    values = [[_get_values(x),type(x)] for x in body.value.elts] if isinstance(body.value,ast.Tuple) else [_get_values(body.value),type(body.value)]
  File "/****/lynie/lynie/lynie.py", line 262, in _get_values
    out = [get_value[type(val)](val,raw) for val in types]
  File "/****/lynie/lynie/lynie.py", line 262, in <listcomp>
    out = [get_value[type(val)](val,raw) for val in types]
  File "/****/lynie/lynie/lynie.py", line 57, in _get_call
    args = _get_values(*call.args)
  File "/****/lynie/lynie/lynie.py", line 262, in _get_values
    out = [get_value[type(val)](val,raw) for val in types]
  File "/****/lynie/lynie/lynie.py", line 262, in <listcomp>
    out = [get_value[type(val)](val,raw) for val in types]
KeyError: <class 'ast.GeneratorExp'>
```

**Comment by JessaTehCrow** [comment]
Hey!

It looks like i forgot to add some of the comprehensions, (namely the dict comprehension and the generator comp).
I thought something like this would happen at some point. 
A new version has been pushed ( this version will be available on pip later today ).

Hopefully this new version fixes what you had problems with.
